apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esrally-pvc
  namespace: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  # storageClassName: standard-rwo
---
apiVersion: v1
kind: Pod
metadata:
  name: esrally
  namespace: elk
  labels:
    app: esrally
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: rally
  tolerations:
    - key: "apptype"
      value: "rally"
      effect: "NoSchedule"
      operator: "Equal"
  securityContext:
    runAsUser: 1000
    fsGroup: 0
  containers:
    - name: esrally
      image: elastic/rally:2.10.0
      command: ["sleep", "infinity"]
      env:
        - name: RALLY_HOME
          value: /rally/.rally
      resources:
        requests:
          cpu: "3"
          memory: "10Gi"
        limits:
          cpu: "4"
          memory: "11Gi"
      volumeMounts:
        - name: esrally-data
          mountPath: /rally/.rally
  volumes:
    - name: esrally-data
      persistentVolumeClaim:
        claimName: esrally-pvc
  restartPolicy: Always