apiVersion: v1
kind: Pod
metadata:
  name: esrally
  namespace: elk
  labels:
    app: esrally
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: rally
  tolerations:
    - key: "apptype"
      value: "rally"
      effect: "NoSchedule"
      operator: "Equal"
  securityContext:
    runAsUser: 0
  containers:
    - name: esrally
      image: elastic/rally:2.10.0
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "3"
          memory: "10Gi"
        limits:
          cpu: "4"
          memory: "11Gi"
  restartPolicy: Always